services:
  # MongoDB for development (no auth)
  mongodb:
    image: mongo:7.0
    container_name: wadm-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - wadm-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    command: ["--storageEngine", "wiredTiger"]

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: wadm-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wadm-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  wadm-network:
    driver: bridge
