services:
  # FastAPI Application
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/cloud_marketdata
      - REDIS_URI=redis://:redis123@redis:6379/0
      - LOG_LEVEL=INFO
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./src:/app/src:ro
      - ./config:/app/config:ro
    restart: unless-stopped
    networks:
      - marketdata

  # MongoDB Database - Latest 7.x (sin auth para desarrollo)
  mongodb:
    image: mongo:7.0-jammy
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=cloud_marketdata
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongodb-init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - marketdata

  # Redis Cache & Pub/Sub - Latest 7.x
  redis:
    image: redis:7.2-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru --requirepass redis123
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - marketdata

  # Redis Commander (Development)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - dev
    networks:
      - marketdata

volumes:
  mongodb_data:
  redis_data:

networks:
  marketdata:
    driver: bridge
